---
title: "Ejercicios:  Repaso de combinatoria y conjuntos. Parte 2"
author: ""
date: ""
output:
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
  word_document:
    toc: yes
    toc_depth: '2'
toccolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache=TRUE)
options(scipen=999)
```



# Ejercicios de Combinatoria parte 2

En todas las resoluciones se deja como ejercicio cómo generar todos los objetos combinatorios con la librería `gtools` o de otra manera. 


## Problema 1

¿De cuantos modos diferentes se pueden colocar tres libros diferentes en una estantería?

## Problema  2

Seis personas entran en el cine. ¿De cuantos modos diferentes se pueden sentar en una fila?


## Problema 3

Tenemos tres premios diferentes para repartir entre una serie de ciudadanos destacados. Si hay 4 candidatos a dichos premios, de cuantos modos se pueden distribuir los premios en dos casos:

* 1. Si un ciudadano puede recibir como máximo un premio
* 2. Si un ciudadano puede recibir más de un premio.


## Problema 4

Dado un conjunto de 15 puntos del plano, ¿cuantas líneas se necesitan para juntar todos los posibles pares de puntos? 

## Problema 5

Dada una caja con los siguientes focos; 2 de 25 vatios, 4 de 40 vatios y 4 de 100 vatios, ¿de cuantos modos se pueden elegir 3 de ellos?


## Problema 6

Supongamos que las placas de matrícula de coches se componen de tres letras seguidas de tres dígitos. Si se pueden usar todas las combinaciones posibles, ¿cuantas placas diferentes se podrían formar?

## Problema 7

 ¿De cuantos modos diferentes se pueden enfrentar en un partido 2 equipos de una liga que tenga 8?


## Problema 8

En un almacén hay cajas rojas y verdes. 
    - ¿De cuantas formas se pueden colocar en fila 20 cajas si 15 son rojas y 5 son verdes? 
    - ¿Y si hay 10 de cada color?



