---
title: "Ejercicios:  Repaso de combinatoria y conjuntos. Parte  1"
author: ""
date: ""
output:
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
  word_document:
    toc: yes
    toc_depth: '2'
toccolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache=TRUE)
options(scipen=999)
```


# Ejercicios de Combinatoria parte 1

Breves soluciones de los problemas

## Problema 1.

En una carrera en la que participan diez caballos ¿de cuántas maneras diferentes se pueden dar los cuatro primeros lugares?

## Problema 2

Una empresa de reciente creación encarga a un diseñador gráfico la elaboración del su logotipo, indicando que ha de seleccionar exactamente tres colores de una lista de seis. ¿Cuántos grupos tienen para elegir el diseñador?


## Problema 3.

¿Cuántas palabras diferentes, de cuatro letras, se pueden formar con la palabra byte?

## Problema 4. 

¿De cuantas maneras diferentes se pueden elegir el director y el subdirector de un departamento formado por 50 miembros?

## Problema 5 

Con once empleados ¿cuántos comités de empresa de cinco personas se pueden formar?


## Problema 6

¿Cuántas maneras distintas hay de colocar quince libros diferentes en una estantería si queremos que el de Probabilidades esté el primero y el de Estadística en el tercero?

## Problema 7 

¿Cuántos caracteres diferentes podemos formar utilizando a lo sumo a tres símbolos de los utilizados en el alfabeto Morse?

## Problema 8

Un supermercado organiza una rifa con un premio de una botella de cava para todas las papeletas que tengan las dos últimas cifras iguales a las correspondientes dos últimas cifras del número premiado en el sorteo de Navidad. Supongamos que todos los décimos tienen cuatro cifras y que existe un único décimo (participación) de cada numeración ¿Cuántas botellas repartirá el supermercado?


## Problema 9

¿Cuántas palabras diferentes podemos formar con todas las letras de la palabra estadística?


## Problema 10

En una tienda de regalos hay relojes de arena con cubetas de colores, y no hay diferencia alguna entre las dos cubetas que forman cada reloj. Si hay cuatro colores posibles y el color de los dos recipientes puede coincidir ¿cuántos modelos de reloj de arena puede ofrecer el establecimiento?

## Problema 11

En una partida de parchís gana aquel jugador que consigue alcanzar antes con sus cuatro fichas la llegada. Si hay cuatro jugadores y la partida continua hasta que todos han completado el recorrido ¿cuántos órdenes de llegadas hay para la dieciséis fichas?


## Problema 12

Se han de repartir cinco becas entre diez españoles y seis extranjeros, de manera que se den tres a españoles y dos a extranjeros ¿De cuántas maneras se puede hacer el reparto?